# Secret 예시 — OpenAI 또는 Gemini 중 하나만 있으면 됨
#
# OpenAI 사용 시:
#   kubectl create secret generic rag-ingestion-secret -n rag \
#     --from-literal=MINIO_ACCESS_KEY='...' \
#     --from-literal=MINIO_SECRET_KEY='...' \
#     --from-literal=OPENAI_API_KEY='sk-...'
#
# Gemini 사용 시 (Job/CronJob에 EMBEDDING_PROVIDER=gemini 설정):
#   kubectl create secret generic rag-ingestion-secret -n rag \
#     --from-literal=MINIO_ACCESS_KEY='...' \
#     --from-literal=MINIO_SECRET_KEY='...' \
#     --from-literal=GEMINI_API_KEY='...'
#
# MinIO는 devops/minio 시크릿에서 복사 가능:
#   MINIO_USER=$(kubectl get secret minio -n devops -o jsonpath='{.data.rootUser}' | base64 -d)
#   MINIO_PASS=$(kubectl get secret minio -n devops -o jsonpath='{.data.rootPassword}' | base64 -d)
#
apiVersion: v1
kind: Secret
metadata:
  name: rag-ingestion-secret
  namespace: rag
type: Opaque
stringData:
  MINIO_ACCESS_KEY: "<MinIO access key>"
  MINIO_SECRET_KEY: "<MinIO secret key>"
  OPENAI_API_KEY: "<OpenAI API key, omit if using Gemini>"
  GEMINI_API_KEY: "<Gemini API key, omit if using OpenAI>"
