apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tz-py-crawler-job
spec:
#  schedule: "* * * * *" # run every minute
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: jenkins
          containers:
          - name: tz-py-crawler-job
            image: doogee323/tz-py-crawler:35
#            image: ${REPOSITORY_TAG}
            imagePullPolicy: IfNotPresent
            args:
            - /usr/bin/python3
            - /code/youtube/cli.py
            - -l
            - /mnt/list.txt
            volumeMounts:
              - name: local-persistent-storage
                mountPath: /mnt
          volumes:
            - name: local-persistent-storage
              persistentVolumeClaim:
                claimName: tz-pvc
          restartPolicy: OnFailure

#            args:
#            - /usr/bin/python3
#            - /code/youtube/cli.py
#            - -l
#            - /mnt/list.txt


#            args:
#            - /usr/sleep
#            - "10000000"
