apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: ca-secret

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-signed-cert
  namespace: default
spec:
  secretName: ca-signed-cert-tls
  duration: 8760h
  renewBefore: 360h
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: ca-issuer
  commonName: test.default.topzone-k8s.topzone.me
  dnsNames:
    - test.default.topzone-k8s.topzone.me
    - consul.default.topzone-k8s.topzone.me
    - vault.default.topzone-k8s.topzone.me
    - consul-server.default.topzone-k8s.topzone.me
    - argocd.default.topzone-k8s.topzone.me
    - jenkins.default.topzone-k8s.topzone.me
    - harbor.harbor.topzone-k8s.topzone.me
    - grafana.default.topzone-k8s.topzone.me
    - prometheus.default.topzone-k8s.topzone.me
    - alertmanager.default.topzone-k8s.topzone.me
    - vagrant-demo-app.devops-dev.topzone-k8s.topzone.me

